{% set name = "web3" %}
{% set version = "7.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d82c78007c280e478b3920cd56658df17f2f76af584ee3318df6b60d4944b8a2

build:
  number: 1
  skip: false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - eth-abi >=5.0.1
    - eth-account >=0.13.6
    - eth-hash[pycryptodome] >=0.5.1
    - eth-typing >=5.0.0
    - eth-utils >=5.0.0
    - hexbytes >=1.2.0
    - aiohttp >=3.7.4.post0
    - pydantic >=2.4.0
    - pywin32 >=223  # [win]
    - requests >=2.23.0
    - typing-extensions >=4.0.1
    - types-requests >=2.0.0
    - websockets >=10.0.0,<16.0.0
    - pyunormalize >=15.0.0

test:
  imports:
    - web3
    - ens

about:
  home: https://github.com/ethereum/web3.py
  summary: Web3.py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
