{% set name = "web3" %}
{% set version = "5.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94b3e6dc1ce7e921322ffa188960c6853f276060b0741a738fe7ba407b4cf063

build:
  number: 1
  # skip due to hypothesis < 4 not playing nice with pytest https://github.com/ethereum/eth-abi/issues/143 and https://github.com/HypothesisWorks/hypothesis/issues/1943
  skip: true  # [py==38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-markdown
  run:
    - python
    - eth-abi >=2.0.0b6,<3.0.0
    - eth-account >=0.5.2,<0.6.0
    - eth-hash >=0.2.0,<1.0.0
    - eth-typing >=2.0.0,<3.0.0
    - eth-utils >=1.8.4,<2.0.0
    - hexbytes >=0.1.0,<1.0.0
    - ipfshttpclient >=0.4.13,<1
    - jsonschema >=3.2.0,<4.0.0
    - lru-dict >=1.1.6,<2.0.0
    - protobuf >=3.10.0,<4
    - pywin32 >=223  # [win]
    - requests >=2.16.0,<3.0.0
    - typing-extensions >=3.7.4.1,<4  # [py<38]
    - websockets >=8.1.0,<9.0.0

test:
  imports:
    - web3
    - ens
    - ethpm

about:
  home: https://github.com/ethereum/web3.py
  summary: Web3.py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
