{% set name = "web3" %}
{% set version = "5.31.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74732fbd4b2e2baff9d0ac61f268b3e7b25b09ca6572d619390a9d782c2289f2

build:
  number: 0
  skip: false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - aiohttp >=3.7.4.post0,<4
    - eth-abi >=2.0.0b6,<3.0.0
    - eth-account >=0.5.9,<0.6.0
    - eth-hash[pycryptodome] >=0.2.0,<1.0.0
    - eth-rlp <0.3
    - eth-typing >=2.0.0,<3.0.0
    - eth-utils >=1.9.5,<2.0.0
    - hexbytes >=0.1.0,<1.0.0
    - ipfshttpclient ==0.8.0a2
    - jsonschema >=3.2.0,<5
    - lru-dict >=1.1.6,<2.0.0
    - protobuf ==3.19.4  # [py!=310]
    - protobuf >=3.19.4,<4  # [py==310]
    - pywin32 >=223  # [win]
    - requests >=2.16.0,<3.0.0
    - typing-extensions >=3.7.4.1,<5  # [py<38]
    - websockets >=9.1.0,<10  # [py!=310]
    - websockets >=10,<11  # [py==310]


test:
  imports:
    - web3
    - ens
    - ethpm

about:
  home: https://github.com/ethereum/web3.py
  summary: Web3.py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
