{% set name = "web3" %}
{% set version = "6.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81a68519ff4416eee7f16d4dbc498e70deb90908c7c1d7bebc950e5f3d1f29d5

build:
  number: 0
  skip: false
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - aiohttp >=3.7.4.post0
    - eth-abi >=4.0.0
    - eth-account >=0.8.0
    - eth-hash[pycryptodome] >=0.5.1
    - eth-typing >=3.0.0
    - eth-utils >=2.1.0
    - hexbytes >=0.1.0,<0.4.0
    - jsonschema >=4.0.0
    - lru-dict >=1.1.6,<1.3.0
    - protobuf >=4.21.6
    - pywin32 >=223  # [win]
    - requests >=2.16.0
    - typing-extensions >=4.0.1  # [py<38]
    - websockets >=10.0.0
    - pyunormalize >=15.0.0

test:
  imports:
    - web3
    - ens
    - ethpm

about:
  home: https://github.com/ethereum/web3.py
  summary: Web3.py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
